### PR TITLE
Feature/test tify pt4

### PR DESCRIPTION
**Pull request by punalsc**
Hi All,

Would anybody be able to have a look at this PR.

Thanks

### CODE REVIEW

**Comment by AshGDS** [comment]
The code is fine - I do however have one small question. At the start of the manifest, we are including the correct height and width for all images. Towards the end, a lot of the images are using incorrect widths and heights. 

I understand we aren't following IIIF standards anyways by having all these different records in one manifest, but would having the incorrect width and height for these images in the manifest affect tify testing?

If this could potentially be a problem, some of the canvases widths and heights would need to be changed (there is a width/height parameter at the top and bottom of each canvas object):

- "WO 95/1097/9" canvases from @punalsc 
- "C14053843"  canvases from @punalsc 
- "WO-95-1486-1" canvas from @JamesWChan (this is only 1 pixel off, so is probably not an issue)
- "Will of Reynold Williams of Much Wollaston, Shropshire" from @ARBaynes 

This is likely a non-issue, as Tify seems to have no problems rendering and manipulating the images when they have incorrect widths/heights in the manifest. If it's agreed that it is a non-issue, I will merge the branch.

Thanks 👍

**Comment by punalsc** [comment]
Hi @AshTNA ,

That's a good observation and It's something i've been thinking of as well. I've done an experiment to see how tify manages the images without any image size properties and it seems to be rendering it just fine. So for now i will remove them from each image object, and we can add them later if we feel it's a requirement.

Thanks 🙂

**Review by AshGDS — CHANGES_REQUESTED** [review]
As discussed, we need to double check the UV/Mirador/Tify are working if something is incorrect (like image heights and widths), or after removing data from the manifest. Thanks 👍

**Comment by AshGDS** [comment]
As discussed, the manifest needed the height and width parameters for compatibility with Mirador, so they have been left in.

**Pull request merged**
