### PR TITLE
Simplify manifest.json to minimum required by TIFY

### PR DESCRIPTION
**Pull request by gtvj**
This PR relates to this issue https://github.com/nationalarchives/Subscription-Offering/issues/288

Removes all but one image and all properties that are not required by TIFY and which do not provide other uses.

### CODE REVIEW

**Comment by gtvj** [comment]
@punalsc - could you just check that TIFY is working OK for you with this reduced `manifest.json`

**Comment by gtvj** [comment]
Hi @ItsMeSami @Puththiran - just copying you in on this so you can see the shape the `manifest.json` is taking

**Comment by gtvj** [comment]
Hi @punalsc - I've implemented the changes discussed earlier today.

**Comment by gtvj** [comment]
Hi @punalsc - might you be able to look at this PR today?

**Review by punalsc — CHANGES_REQUESTED** [review]
Could we possibly remove the Mirador and Universal viewer links from the `Readme`, as it's not required anymore?
Lines 49 and 50

**Review by punalsc — CHANGES_REQUESTED** [review]
HI @gtvj ,
Just to recap on our previous discussion, we will introduce one more image inside the `manifest.json` and delete any unused images from the image folder.

Thanks

**Comment by gtvj** [comment]
Thanks @punalsc - I've made the changes you requested.

**Review by punalsc — APPROVED** [review]

**Pull request merged**
